FROM node:alpine AS builder
WORKDIR /app
COPY . . 
RUN npm install

RUN npm run build

RUN rm -rf node_modules package-lock.json

FROM nginx:latest

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf  /etc/nginx/conf.d
 CMD ["nginx", "-g", "daemon off;"]

ENTRYPOINT []
EXPOSE 3000